# Use an official Node.js runtime as a base image
FROM node:alpine

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json .

# Install app dependencies
RUN npm ci

# Copy the rest of the application code
COPY . .

# Expose the port that the app will run on
EXPOSE 5000

# Define the command to run your application
CMD ["npm", "start"]